// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: cwatch

#include "../ui.h"

void ui_ScreenHomeImg_screen_init(void)
{
    ui_ScreenHomeImg = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenHomeImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenHomeImg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenHomeImg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHomeImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_ScreenHomeImg, &ui_img_img_img1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ScreenHomeImg = ui_ScreenHomeImg;

}
