// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: cwatch

#include "../ui.h"

void ui_ScreenMenu_screen_init(void)
{
    ui_ScreenMenu = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_ScreenMenu, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_flex_flow(ui_ScreenMenu, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ScreenMenu, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarm = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_alarm, &ui_img_icon_alarm_png);
    lv_obj_set_width(ui_alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alarm, -69);
    lv_obj_set_y(ui_alarm, 46);
    lv_obj_set_align(ui_alarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_clock, &ui_img_icon_clock_png);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clock, -1);
    lv_obj_set_y(ui_clock, -160);
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_itunes = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_itunes, &ui_img_icon_itunes_png);
    lv_obj_set_width(ui_itunes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itunes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_itunes, -1);
    lv_obj_set_y(ui_itunes, -160);
    lv_obj_set_align(ui_itunes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_itunes, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_itunes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_camera = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_camera, &ui_img_icon_camera_png);
    lv_obj_set_width(ui_camera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_camera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_camera, -99);
    lv_obj_set_y(ui_camera, -61);
    lv_obj_set_align(ui_camera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_camera, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_camera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mail = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_mail, &ui_img_icon_mail_png);
    lv_obj_set_width(ui_mail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mail, -1);
    lv_obj_set_y(ui_mail, -160);
    lv_obj_set_align(ui_mail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mail, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_mail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_maps = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_maps, &ui_img_icon_maps_png);
    lv_obj_set_width(ui_maps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maps, -1);
    lv_obj_set_y(ui_maps, -160);
    lv_obj_set_align(ui_maps, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_maps, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_maps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_phone = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_phone, &ui_img_icon_phone_png);
    lv_obj_set_width(ui_phone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phone, -1);
    lv_obj_set_y(ui_phone, -160);
    lv_obj_set_align(ui_phone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_phone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_phone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_photos = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_photos, &ui_img_icon_photos_png);
    lv_obj_set_width(ui_photos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_photos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_photos, -161);
    lv_obj_set_y(ui_photos, -159);
    lv_obj_set_align(ui_photos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_photos, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_photos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pulse = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_pulse, &ui_img_icon_pulse_png);
    lv_obj_set_width(ui_pulse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pulse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pulse, -1);
    lv_obj_set_y(ui_pulse, -160);
    lv_obj_set_align(ui_pulse, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pulse, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_pulse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reminders = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_reminders, &ui_img_icon_reminders_png);
    lv_obj_set_width(ui_reminders, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reminders, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reminders, -1);
    lv_obj_set_y(ui_reminders, -160);
    lv_obj_set_align(ui_reminders, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reminders, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_reminders, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_settings, &ui_img_icon_settings_png);
    lv_obj_set_width(ui_settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settings, -1);
    lv_obj_set_y(ui_settings, -160);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stocks = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_stocks, &ui_img_icon_stocks_png);
    lv_obj_set_width(ui_stocks, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stocks, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stocks, -1);
    lv_obj_set_y(ui_stocks, -160);
    lv_obj_set_align(ui_stocks, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stocks, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_stocks, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timer = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_timer, &ui_img_icon_timer_png);
    lv_obj_set_width(ui_timer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer, -1);
    lv_obj_set_y(ui_timer, -160);
    lv_obj_set_align(ui_timer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_timer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wallet = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_wallet, &ui_img_icon_wallet_png);
    lv_obj_set_width(ui_wallet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wallet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wallet, 0);
    lv_obj_set_y(ui_wallet, -160);
    lv_obj_set_align(ui_wallet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wallet, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wallet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_weather, &ui_img_icon_weather_png);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, 0);
    lv_obj_set_y(ui_weather, -160);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_workout = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_workout, &ui_img_icon_workout_png);
    lv_obj_set_width(ui_workout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_workout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_workout, 0);
    lv_obj_set_y(ui_workout, -160);
    lv_obj_set_align(ui_workout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_workout, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_workout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_world = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_world, &ui_img_icon_world_png);
    lv_obj_set_width(ui_world, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_world, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_world, 0);
    lv_obj_set_y(ui_world, -160);
    lv_obj_set_align(ui_world, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_world, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_world, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imessage = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_imessage, &ui_img_icon_imessage_png);
    lv_obj_set_width(ui_imessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imessage, -1);
    lv_obj_set_y(ui_imessage, -160);
    lv_obj_set_align(ui_imessage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imessage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calendar = lv_image_create(ui_ScreenMenu);
    lv_image_set_src(ui_calendar, &ui_img_icon_calendar_png);
    lv_obj_set_width(ui_calendar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calendar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calendar, -194);
    lv_obj_set_y(ui_calendar, -157);
    lv_obj_set_align(ui_calendar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calendar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
