// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: cwatch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
lv_obj_t * ui_ScreenMenu;
lv_obj_t * ui_alarm;
lv_obj_t * ui_clock;
lv_obj_t * ui_itunes;
lv_obj_t * ui_camera;
lv_obj_t * ui_mail;
lv_obj_t * ui_maps;
lv_obj_t * ui_phone;
lv_obj_t * ui_photos;
lv_obj_t * ui_pulse;
lv_obj_t * ui_reminders;
lv_obj_t * ui_settings;
lv_obj_t * ui_stocks;
lv_obj_t * ui_timer;
lv_obj_t * ui_wallet;
lv_obj_t * ui_weather;
lv_obj_t * ui_workout;
lv_obj_t * ui_world;
lv_obj_t * ui_imessage;
lv_obj_t * ui_calendar;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenHomeImg
void ui_ScreenHomeImg_screen_init(void);
lv_obj_t * ui_ScreenHomeImg;
// CUSTOM VARIABLES
lv_obj_t * uic_ScreenHomeImg;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMenu_screen_init();
    ui_ScreenHomeImg_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMenu);
}
