// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: cwatch

#ifndef _CWATCH_UI_H
#define _CWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
extern lv_obj_t * ui_ScreenMenu;
extern lv_obj_t * ui_alarm;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_itunes;
extern lv_obj_t * ui_camera;
extern lv_obj_t * ui_mail;
extern lv_obj_t * ui_maps;
extern lv_obj_t * ui_phone;
extern lv_obj_t * ui_photos;
extern lv_obj_t * ui_pulse;
extern lv_obj_t * ui_reminders;
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_stocks;
extern lv_obj_t * ui_timer;
extern lv_obj_t * ui_wallet;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_workout;
extern lv_obj_t * ui_world;
extern lv_obj_t * ui_imessage;
extern lv_obj_t * ui_calendar;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenHomeImg
void ui_ScreenHomeImg_screen_init(void);
extern lv_obj_t * ui_ScreenHomeImg;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenHomeImg;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icon_alarm_png);    // assets/icon/alarm.png
LV_IMG_DECLARE(ui_img_icon_clock_png);    // assets/icon/clock.png
LV_IMG_DECLARE(ui_img_icon_itunes_png);    // assets/icon/itunes.png
LV_IMG_DECLARE(ui_img_icon_camera_png);    // assets/icon/camera.png
LV_IMG_DECLARE(ui_img_icon_mail_png);    // assets/icon/mail.png
LV_IMG_DECLARE(ui_img_icon_maps_png);    // assets/icon/maps.png
LV_IMG_DECLARE(ui_img_icon_phone_png);    // assets/icon/phone.png
LV_IMG_DECLARE(ui_img_icon_photos_png);    // assets/icon/photos.png
LV_IMG_DECLARE(ui_img_icon_pulse_png);    // assets/icon/pulse.png
LV_IMG_DECLARE(ui_img_icon_reminders_png);    // assets/icon/reminders.png
LV_IMG_DECLARE(ui_img_icon_settings_png);    // assets/icon/settings.png
LV_IMG_DECLARE(ui_img_icon_stocks_png);    // assets/icon/stocks.png
LV_IMG_DECLARE(ui_img_icon_timer_png);    // assets/icon/timer.png
LV_IMG_DECLARE(ui_img_icon_wallet_png);    // assets/icon/wallet.png
LV_IMG_DECLARE(ui_img_icon_weather_png);    // assets/icon/weather.png
LV_IMG_DECLARE(ui_img_icon_workout_png);    // assets/icon/workout.png
LV_IMG_DECLARE(ui_img_icon_world_png);    // assets/icon/world.png
LV_IMG_DECLARE(ui_img_icon_imessage_png);    // assets/icon/imessage.png
LV_IMG_DECLARE(ui_img_icon_calendar_png);    // assets/icon/calendar.png
LV_IMG_DECLARE(ui_img_img_img1_png);    // assets/img/img1.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
